CREATE TABLE Test (id int)
INSERT INTO Test (Id) VALUES (1)
SELECT * FROM Test

SELECT * FROm sys.databases WHERE name = 'DbOnMounts'


ALTER DATABASE DbOnMounts SET OFFLINE WITH ROLLBACK IMMEDIATE
ALTER DATABASE DbOnMounts SET ONLINE WITH ROLLBACK IMMEDIATE