// DTU consumption > 90%
let dtStart = ago(7d);
let dtEnd = ago(6d);
let DatabaseNameInResourceId = "/<DBNAME>";
AzureMetrics
| where ResourceProvider=="MICROSOFT.SQL" 
| where ResourceId contains "/SERVERS/" 
| where ResourceId contains "/DATABASES/" 
| where ResourceId contains DatabaseNameInResourceId 
| where MetricName == "dtu_consumption_percent" 
| where Maximum > 90
| project TimeGenerated , ResourceId , MetricName , Maximum 
